export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

// For Async calls we have to handle three cases:

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILURE = 'REQUEST_ROBOTS_FAILURE';

